var courses = [
    {
        "name": "Learn Web Design with Dylan",
        "image": "https://i.ibb.co/wpW1SvM/zan-BTz-LUhq4z0-U-unsplash.jpg",
        "instructor": "Bob Dylan",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 120,
    },
    {
        "name": "Learn Web Development with Lenon",
        "image": "https://i.ibb.co/7vwfWw5/startup-849804-1920.jpg",
        "instructor": "Jhon Lenon",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 190,
    },
    {
        "name": "Learn Web Development with Elvis",
        "image": "https://i.ibb.co/r7ZKjmX/business-2717063-1920.jpg",
        "instructor": "Elite Team",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 100,
    },
    {
        "name": "Learn Web Development with Led Zeppelin",
        "image": "https://i.ibb.co/RTgzJN0/claudio-schwarz-purzlbaum-q8k-R-ie6-Wn-I-unsplash.jpg",
        "instructor": "Robert Plant",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 100,
    },
    {
        "name": "Software Testing & Quality Assurance using Selenium",
        "image": "https://i.ibb.co/g6579Lf/destin-gong-pl9-Drj-AMV6-I-unsplash.jpg",
        "instructor": "Ahmed Galib",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 456,
    },
    {
        "name": "Web Development with React & Node.js",
        "image": "https://i.ibb.co/0G7Nk6k/iswanto-arif-PFTv-Py-Te8-UU-unsplash.jpg",
        "instructor": "Mehedi Hasan Chhoton",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 230,
    },
    {
        "name": "Web App Development with Laravel & Vue",
        "image": "https://i.ibb.co/BcJ10WG/laptop-2838921-1920-1.jpg",
        "instructor": "Elton Jhon",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 199,
    },
    {
        "name": "ERP Functional Workshop for Corporate Efficiency",
        "image": "https://i.ibb.co/ZV4sY3Y/peter-olexa-QR9-EAho-IHs-I-unsplash.jpg",
        "instructor": "Brad Traverse",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 299,
    },
    {
        "name": "Cloud Journey with AWS (Beginner to Advance level)",
        "image": "https://i.ibb.co/gPGPRnM/phil-desforges-IUrd-CYJm1u4-unsplash.jpg",
        "instructor": "Stefen Gridder",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 199,
    },
    {
        "name": "The Complete SQL Bootcamp 2020: Go from Zero to Hero",
        "image": "https://i.ibb.co/yft0rjm/student-849826-1920.jpg",
        "instructor": "Peter Parker",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 300,
    },
    {
        "name": "SQL Bootcamp 2020: Go from Zero to Hero",
        "image": "https://i.ibb.co/HnmwtC9/web-3963945-1920.jpg",
        "instructor": "Moin Ali",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 199,
    },
    {
        "name": "iOS 13 & Swift 5 - The Complete iOS App Development Bootcamp",
        "image": "https://i.ibb.co/yftjfKm/social-3408791-1920.jpg",
        "instructor": "Shelly Tunner",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 299,
    },
    {
        "name": "JavaScript - The Complete Guide 2020 (Beginner + Advanced ",
        "image": "https://i.ibb.co/124ny1F/web-design-1953129-1920.jpg",
        "instructor": "Nowaaz Uddin",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 899,
    },
    {
        "name": "Advanced CSS and Sass: Flexbox, Grid, Animations and More!",
        "image": "https://i.ibb.co/7z1JTpt/plans-1867745-1280.jpg",
        "instructor": "Dell Karnell",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 599,
    },
    {
        "name": "Understanding TypeScript - 2020 Edition",
        "image": "https://i.ibb.co/MNMYyhd/student-849821-1920.jpg",
        "instructor": "Purto Shenon",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 344,
    },
    {
        "name": "Microservices with Node JS and React",
        "image": "https://i.ibb.co/wpW1SvM/zan-BTz-LUhq4z0-U-unsplash.jpg",
        "instructor": "Jonny neimer",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 787,
    },
    {
        "name": "Docker and Kubernetes: The Complete Guide",
        "image": "https://i.ibb.co/MNMYyhd/student-849821-1920.jpg",
        "instructor": "Andy griss",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 233,
    },
    {
        "name": "GitLab CI: Pipelines, CI/CD and DevOps for Beginners",
        "image": "https://i.ibb.co/MNMYyhd/student-849821-1920.jpg",
        "instructor": "Shourov Hasan",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 566,
    },
    {
        "name": "Monitoring and Alerting with Prometheus",
        "image": "https://i.ibb.co/7vwfWw5/startup-849804-1920.jpg",
        "instructor": "Rabbil hasan",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 777,
    },
    {
        "name": "Learn DevOps: The Complete Kubernetes Course",
        "image": "https://i.ibb.co/kJPPpvT/jesse-smith-R0c-JIc-Bp-E70-unsplash.jpg",
        "instructor": "Neil Petter",
        "description": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente numquam ea possimus quis eius aliquam!",
        "price": 699,
    },
];

export default courses;